language: python
python:
    - "3.6"
    - "3.6-dev"
install:
    - pip install coveralls flake8 statsmodels matplotlib graphviz mock scipy mypy wheel
    - python setup.py install
script:
    - coverage run --source=pytree test.py
    - flake8 pytree test.py setup.py --max-line-length=120
    - mypy pytree --ignore-missing-imports
after_success:
    - coveralls
before_deploy:
    - python setup.py bdist_wheel
    - python setup.py sdist
    - ls -l dist/*{tar.gz,whl}
    - unzip -p dist/*.whl | sha256sum
    - tar -Oxf dist/*.tar.gz | sha256sum
deploy:
    provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: dist/*{tar.gz,whl}
    skip_cleanup: true
    on:
        branch: master
        tags: true
