language: python

python:
    - "3.6"
    - "3.6-dev"

install:
    - pip install coveralls flake8 statsmodels matplotlib graphviz mock scipy
    - python setup.py install

script:
    - coverage run --source=pytree test.py
    - flake8 pytree test.py setup.py --max-line-length=120

after_success:
    - coveralls
