name: Pycewise

on: [push]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: [3.6, 3.7, 3.8]
        steps:
            - name: Set up the repository
              uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python --version
                pip install --upgrade pip
                pip --version
                pip install --upgrade --upgrade-strategy eager twine wheel matplotlib graphviz mock pandas coveralls flake8 mypy
                pip freeze
            - name: Build and test
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                python setup.py bdist_wheel
                pip install dist/*.whl
                coverage run --source=pycewise test.py
                twine check dist/*
                flake8 pycewise test.py setup.py --max-line-length=120
                mypy pycewise --ignore-missing-imports
                coveralls debug --service=gihtub
            - name: Save the build files
              uses: actions/upload-artifact@master
              with:
                  name: package
                  path: dist/*.whl
    publish:
        runs-on: ubuntu-latest
        needs: test
        if: github.event_name == 'push' && contains(github.ref, '/tags/')
        steps:
            - name: Restore the build files
              uses: actions/download-artifact@master
              with:
                  name: package
                  path: .
            - name: Upload the package to the release
              uses: svenstaro/upload-release-action@v2
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: ./*.whl
                  overwrite: true
                  file_glob: true
                  tag: ${{ github.ref }}
